# Generated by Django 5.2.4 on 2025-07-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
